### PR TITLE
add EL 9 support + ntsdumpdir

### PR DESCRIPTION
**Pull request by duritong**

### CODE REVIEW

**Comment by duritong** [comment]
I don't think it's my fault that then CentOS 9 tests are failing. Since the systemd service can't write to /run/chrony/chrony.pid which works fine on a VM.

Anyone any ideas?

**Comment by root-expert** [comment]
Maybe that's a SELinux problem?

**Comment by jcpunk** [comment]
Can you try rebasing off HEAD to see if that helps?

**Comment by duritong** [comment]
ntsdumpdir got added with cc0af5601a55e3bfdcff651339d49813f32cf692 and EL 9 support will hopefully make it with #151

**Pull request closed without merging**
