### PR TITLE
Fix wrong end-tag resulting in blank line.

### PR DESCRIPTION
**Pull request by chrekh**

### CODE REVIEW

**Comment by chrekh** [comment]
> how could we regression test changes between module upgrades anyway??

Perhaps we could add ```.without_content(%r{^\s*\n\s*$})``` to test for double blank lines?

**Comment by chrekh** [comment]
> Perhaps we could add `.without_content(%r{^\s*\n\s*$})` to test for double blank lines?

I tried that, and imediately found an other bug

```
<% if $chrony::refclocks { -%>

<%   $chrony::refclocks.each |$driver| { -%>
refclock <%= $driver.flatten.join(' ') %>
<%   } -%>
<% } -%>
```

Is adding a blank line when refclocks is []

**Comment by igalic** [comment]
you want to test whether that is empty then, or else give it undef as default

**Comment by chrekh** [comment]
> you want to test whether that is empty then, or else give it undef as default

I think we should add type constrain Array to it in init.pp instead. And just remove the if test.

**Comment by igalic** [comment]
the `if` controls the insertion of a newline `refclock`, so the test *should* be for `empty()`

**Comment by chrekh** [comment]
> the `if` controls the insertion of a newline `refclock`, so the test _should_ be for `empty()`

And ofcourse you are right. The `if` is still needed even if we require refclock to be Array. I'll prepare a PR for that.

**Comment by igalic** [comment]
since this pr is about fixing whitespace, i'd do that here.

**Comment by chrekh** [comment]
Make sense, ok, I'll do that.

**Comment by chrekh** [comment]
Ok, I'll rebase to master (because the added gentoo tests) and add a test for double blank lines. I'll add a separate PR later for restructuring the tests to match the gentoo case.

**Pull request merged**
